version: '3.8'

services:
  nginx:
    image: nginx
    container_name: nginx-test
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - /root/ssl/letsencrypt/live:/etc/nginx/ssl/live
      - /root/ssl/letsencrypt/archive:/etc/nginx/ssl/archive
    networks:
      - nginx
      - nextcloud
      - pleroma
    ports:
      - 80:80
      - 443:443

networks:
  nginx:
    internal: true
    name: nginx
  nextcloud:
    name: nextcloud
    external: true
  pleroma:
    name: pleroma
    external: true
